In [2]:
import pandas as pd;

In [3]:
doelpunten_df = pd.read_csv('./csv/doelpunten_onverwerkd.csv')
klassement_df = pd.read_csv('./csv/klassement_onverwerkd.csv')
wedstrijden_df = pd.read_csv('./csv/wedstrijden_onverwerkd.csv')

In [4]:
df_total = pd.merge(wedstrijden_df,doelpunten_df,on=['id_match','datum','seizoen','tijd','thuisploeg','uitploeg','uitploeg_stamnummer','thuisploeg_stamnummer'],how='left')

In [5]:
rows_home = df_total[['thuisploeg', 'thuisploeg_stamnummer']].rename(columns={'thuisploeg': 'TeamName', 'thuisploeg_stamnummer': 'StamNumber'})
rows_away = df_total[['uitploeg', 'uitploeg_stamnummer']].rename(columns={'uitploeg': 'TeamName', 'uitploeg_stamnummer': 'StamNumber'})

dim_team_df = pd.concat([rows_home,rows_away])
dim_team_df = dim_team_df.drop_duplicates()
dim_team_df = dim_team_df.reset_index(drop=True)
dim_team_df

                  TeamName  StamNumber
0     Union Saint-Gilloise          10
1                KAS Eupen        4276
2           R Charleroi SC          22
3            RWD Molenbeek          47
4         Royal Antwerp FC           1
5                 KAA Gent           7
6              Club Brugge           3
7        Sint-Truidense VV         373
8            Standard Luik          16
9                 KRC Genk         322
10           Cercle Brugge          12
11     Oud-Heverlee Leuven          18
12          RSC Anderlecht          35
13             KV Mechelen          25
14            KVC Westerlo        2024
15             KV Kortrijk          19
16        SV Zulte Waregem        5381
17             KV Oostende          31
18             RFC Seraing          17
19               Beerschot          13
20               Moeskroen         216
21        Waasland-Beveren        4068
22             KSC Lokeren         282
23               Lierse SK          30
24               RAEC Mons          44
25             KSK Beveren        2300
26                Germinal        3530
27           KSV Roeselare         134
28              AFC Tubize        5632
29           FCV Dender EH        3900
30      Excelsior Mouscron         224
31             FC Brussels        1936
32             La Louviere          94
33          Heusden-Zolder        2614
34         KFC Lommelse SK        1986
35         Eendracht Aalst          90
36           KRC Harelbeke        1615
37  KFC Verbroedering Geel         395
38             KSV Waregem        4451
39                RFC Luik           4
40                 Boom FC          58
41         Racing Mechelen          24
42      Racing Jet Brussel        4549
43           Berchem Sport          28
44      Waterschei SV Thor         553
45      K. Sint-Niklase SK         221
46             Beringen FC         522
47            KSK Tongeren          54
48             KSC Hasselt          37
49          AS Oostende KM          53
50               KFC Diest          41
51       Olympic Charleroi         246
52          RCC Schaerbeek          55
53     Daring Club Brussel           2
54             RFC Tilleur          21
55            KFC Turnhout         148
56            Patro Eisden        3434
57              Vervi√©tois          33

In [8]:

dim_standings_df = klassement_df[['speeldag', 'seizoen', 'id_ploeg', 'stand', 'punten', 'aantal_gewonnen', 'aantal_gelijk', 'aantal_verloren', 'verschil']]
temp_df = dim_team_df.copy()
temp_df['ClubID'] = temp_df.index
merged_df = dim_standings_df.merge(temp_df, left_on='id_ploeg', right_on='StamNumber', how='left')

dim_standings_df = merged_df.drop(columns=['id_ploeg','TeamName','StamNumber'])
dim_standings_df = dim_standings_df.rename(columns={'speeldag':'StandingsPlayday','seizoen':'StandingsYear','stand':'Ranking','punten':'Points','aantal_gewonnen':'Wins','aantal_gelijk':'Ties','aantal_verloren':'Losses','verschil':'GoalDifference'})
dim_standings_df

,StandingsPlayday,StandingsYear,Ranking,Points,Wins,Ties,Losses,GoalDifference,ClubID
0,1,2023,1,3,1,0,0,4,9.0
1,1,2023,2,3,1,0,0,2,0.0
2,1,2023,3,3,1,0,0,1,5.0
3,1,2023,3,3,1,0,0,1,7.0
4,1,2023,3,3,1,0,0,1,4.0
...,...,...,...,...,...,...,...,...,...
35923,30,1960,12,28:32,9,10,11,-16,35.0
35924,30,1960,13,26:34,6,14,10,-15,51.0
35925,30,1960,14,23:37,10,3,17,-16,0.0
35926,30,1960,15,19:41,5,9,16,-24,57.0
35927,30,1960,16,18:42,6,6,18,-28,56.0

In [ ]:
dim_goal_df = doelpunten_df[['id_match','goal_time','goal_team_naam','stand_thuis','stand_uit','real_time_goal']]